

export const MOCK_OBJECTS = {
    USERNAME: 'cypress',
    EMPTY_STRING: '',
    CURR_PAGE: 1,
    LIMIT: 3,
    NaN: NaN,
    LEARNING_OBJECT_NAME: 'testing',
    S3_LOCATION: 'http://s3.amazonaws.com/doc/2006-03-01/',
    S3_MULTIPART_UPLOAD_DATA: {
        uploadId: '123456789',
        completedPart: {
            ETag: 'tag',
            PartNumber: 101,
        },
    },
    LEARNING_OBJECT_ID: '5a70fb5ed45bde3f9d65a88c',
    COLLECTION: {
        name: 'test',
        learningObjects: [],
    },
    LEARNING_OBJECT: {
        author: '5a70fb5ed45bde3f9d65agfd',
        name: 'Input Validation - CS0 - C',
        date: '1523479539862',
        length: 'nanomodule',
        levels: [],
        goals: [],
        outcomes: [],
        materials: {},
        metrics: {},
        published: true,
        publish: '',
        unpublish: '',
        children: [],
        contributors: [],
        lock: {},
        collection: 'nccp',
      },
    TOTAL_RECORDS: 1,
    COLLECTION_META: {
        name: 'test',
        abstracts: [],
    },
    COLLECTION_NAME: 'test',
    MULTIPART_UPLOAD_STATUS: {
        _id: 'id',
        uploadId: 'upload id',
        partsUploaded: 2,
        totalParts: 2,
        fileSize: 134,
        path: 'path',
        bytesUploaded: 132,
        completedParts: [],
        createdAt: 'time',
    },
    LEARNING_OBJECT_FILE: {
        id: '123456789',
        name: 'test',
        fileType: 'text',
        extension: 'txt',
        url: 'url',
        date: 'date',
        fullPath: 'path',
        size: 132,
        description: 'test',
        packageable: true,
    },
    METRICS: {
        saves: 23,
        downloads: 4,
    },
};
