defaults: &defaults
  working_directory: ~/learning-object-service
  docker:
    - image: cyber4all/circleci-aws:docker-git
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image & Unit Test
          command: | 
            docker build -t learning-object-service:$CIRCLE_SHA1 . --build-arg CLARK_DB_URI_TEST=$CLARK_DB_URI_TEST
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Publish Image 
          command: |
            docker tag learning-object-service:$CIRCLE_SHA1 "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}"
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./package.json
              - ./deploy.sh

  elasticsearch-smoke-test:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Clone Elasticsearch Smoke Test Repository 
          command: >-
            cd .. && git clone https://${github_username}:${github_password}@github.com/nvisal1/Elasticsearch-Smoke-Test-Environment.git
      - run: 
          name: Run Environment
          command: |
            cd ../Elasticsearch-Smoke-Test-Environment
            docker-compose up --abort-on-container-exit --exit-code-from test-runner

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/learning-object-service
      - setup_remote_docker
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}"
      - run:
          name: Publish Image 
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            docker tag "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}" "${DOCKER_USER_ORG}/learning-object-service:${SEMVER}"
            docker push "${DOCKER_USER_ORG}/learning-object-service:${SEMVER}"
      - run:
          name: Deploy to ECS
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            export DOCKER_IMAGE="${DOCKER_USER_ORG}/learning-object-service:${SEMVER}"
            chmod +x ./deploy.sh
            sh ./deploy.sh
            
workflows:
  version: 2
  build-and-elasticsearch-smoke-test:
    jobs:
      - build
      - elasticsearch-smoke-test

  build-test-and-deploy-production:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: /master/