defaults: &defaults
  working_directory: ~/learning-object-service
  docker:
    - image: cyber4all/circleci-aws:latest
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: | 
            docker build -t learning-object-service:$CIRCLE_SHA1 .
            mkdir -p docker-image
            docker save -o "docker-image/learning-object-service:${CIRCLE_SHA1}.tar" learning-object-service:$CIRCLE_SHA1
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./docker-image
              - ./package.json
              - ./deploy.sh

  unit-test:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/learning-object-service
      - setup_remote_docker
      - run:
          name: Unit Test Image
          command: |
            docker load < "docker-image/learning-object-service:${CIRCLE_SHA1}.tar"
            docker run -it learning-object-service:$CIRCLE_SHA1 npm test
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Publish Image 
          command: |
            docker tag learning-object-service:$CIRCLE_SHA1 "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}"

  integration-test:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/learning-object-service
      - setup_remote_docker
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}"
      - run:
          name: Run Integration Test
          command: |
            echo docker run -it learning-object-service:$CIRCLE_SHA1 npm test

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/learning-object-service
      - setup_remote_docker
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}"
      - run:
          name: Publish Image 
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            docker tag "${DOCKER_USER_ORG}/learning-object-service:${CIRCLE_SHA1}" "${DOCKER_USER_ORG}/learning-object-service:${SEMVER}"
            docker push "${DOCKER_USER_ORG}/learning-object-service:${SEMVER}"
      - run:
          name: Deploy to ECS
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            export DOCKER_IMAGE="${DOCKER_USER_ORG}/learning-object-service:${SEMVER}"
            chmod +x ./deploy.sh
            sh ./deploy.sh
            
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - unit-test

  build-test-and-deploy-production:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - unit-test:
          requires:
            - build
          filters:
            branches:
              only: /master/
      - integration-test:
          requires:
            - unit-test
          filters:
            branches:
              only: /master/
      - deploy-production:
          requires:
            - integration-test
          filters:
            branches:
              only: /master/